openapi: 3.0.0
info:
  title: Yourflow API
  version: 1.0.0

paths:
  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request - something wrong with data or user already logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: Forbidden - authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/v1/auth/registration:
    post:
      tags:
        - Auth
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                birthday:
                  type: string
                  format: date
                email:
                  type: string
                  format: email
              required:
                - username
                - password
                - birthday
                - email
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request - invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '409':
          description: Conflict - user with such data already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/v1/auth/logout:
    post:
      tags:
        - Auth
      summary: Logout user
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/v1/feed:
    get:
      tags:
        - Feed
      summary: Get pins for feed
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          description: Page number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    header:
                      type: string
                    image:
                      type: string
                    author:
                      type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  # New profile endpoints
  /api/v1/profile:
    get:
      tags:
        - Profile
      summary: Get current user profile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    format: email
                  avatar:
                    type: string
                  username:
                    type: string
                  public_username:
                    type: string
                  about:
                    type: string
                  birthday:
                    type: string
                    format: date
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/v1/profile/password:
    put:
      tags:
        - Profile
      summary: Change password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_password:
                  type: string
              required:
                - new_password
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/v1/profile/avatar:
    put:
      tags:
        - Profile
      summary: Update avatar
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/v1/profile/update:
    patch:
      tags:
        - Profile
      summary: Update profile info
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  # Flow (Pin) endpoints
  /api/v1/flow:
    get:
      tags:
        - Flow
      summary: Get pin by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_liked:
                    type: boolean
                  like_count:
                    type: integer
                  header:
                    type: string
                  description:
                    type: string
                  author:
                    type: string
        '404':
          description: Pin not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    post:
      tags:
        - Flow
      summary: Upload pin image
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    put:
      tags:
        - Flow
      summary: Upload pin text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
                name:
                  type: string
                description:
                  type: string
              required:
                - author
                - name
                - description
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    delete:
      tags:
        - Flow
      summary: Delete pin
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Pin not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  # Board endpoints
  /api/v1/board:
    get:
      tags:
        - Board
      summary: Get board by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  desk_id:
                    type: string
                  desk_name:
                    type: string
                  desk_count:
                    type: integer
                  desk_preview:
                    type: array
                    items:
                      type: string
        '404':
          description: Board not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    post:
      tags:
        - Board
      summary: Create new board
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
                desk_name:
                  type: string
              required:
                - author
                - desk_name
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  # Like endpoint
  /api/v1/like:
    put:
      tags:
        - Like
      summary: Like/unlike pin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pin_id:
                  type: string
              required:
                - pin_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  is_liked:
                    type: boolean
        '401':
          description: Unauthorized
        '404':
          description: Pin not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string